### ISSUE TITLE
fx_cast_bridge not recognized as correct version

### ISSUE THREAD

**Issue by directrix1** [hensm/fx_cast#105]
After upgrading from 0.0.5 to the 0.0.6 xpi and deb on Ubuntu I get Bridge Issue, INCOMPATIBLE, version 0.0.5, expected 0.0.6 . I downloaded the deb and xpi from the releases page and installed them both though. Anyway this prevents it from working since the update.

**Comment by hensm** [comment]
Tested an upgrade on Ubuntu a few days ago and it worked fine. What's the output of these commands?

````sh
dpkg -s fx-cast-bridge
cat /usr/lib/mozilla/native-messaging-hosts/fx_cast_bridge.json
sha256sum /opt/fx_cast/fx_cast_bridge
````
