### ISSUE TITLE
Is there a compatibility list?

### ISSUE THREAD

**Issue by poma** [hensm/fx_cast#111]
I've tried this on a few sites that I use (added them to whitelist too):

- youtube.com
- music.youtube.com
- soundcloud.com
- vk.com

It doesn't appear to work anywhere. No 'cast' button appears on the player, and when I click cast icon in browser toolbar 'tab' and 'screen' are greyed out. Am I doing something wrong or app doesn't work on any of those sites?

**Comment by hensm** [comment]
[Compatibility list](https://github.com/hensm/fx_cast/issues?q=is%3Aissue+label%3Acompat)

YouTube and Soundcloud can have issues, but have worked reliably for me. Tab and screen are greyed out unless mirroring is enabled in settings.

Is your chromecast being detected properly and displayed in the popup?

Post your whitelist entries and any logs from the [extension debug console](https://extensionworkshop.com/documentation/develop/debugging/#developer-tools-toolbox) and web console whilst on YouTube.
