### ISSUE TITLE
403 Error when downloading debian binary via AUR (fx_cast-bin).

### ISSUE THREAD

**Issue by reesericci** [hensm/fx_cast#115]
The .deb file is 403 when trying to download. I tried downloading via AUR and downloading directly.

**Comment by hensm** [comment]
@csicar

**Comment by csicar** [comment]
I just double-checked, that the AUR installation still works. And for me it does.


What happens when you open https://github.com/hensm/fx_cast/releases/download/v0.0.6/fx_cast_bridge-0.0.6-x64.deb ? Do you also get a Http Error 403?

**Comment by reesericci** [comment]
It's back up! Must've been Github/AWS.
