### ISSUE TITLE
[AquosTV/Android/Chromecast] <fx_Cast v0.0.6>

### ISSUE THREAD

**Issue by bogy1980** [hensm/fx_cast#118]
**Firefox64v77.0.1+FX_Cast:0.0.6**
**Youtube.com:**
**App ID (if possible):**

**Issues:**
I've been trying to cast to my Android tv which has built-in chromecast (works fine with chrome, but i don't like chrome) but the television doesn't seem to  react to FX_cast calls...  

on a youtube site i copy pasted the youtube url into fx_cast, and it saw my television, but it would not cast the video succesfully.  (also, i don't know if i needed to copy/paste the url of the youtube video; as the other options didn't give me a clickable cast button.

fxcast starts casting (at least the plugin says so), but no reaction from the television

**Error log (if applicable):**

**Comment by hensm** [comment]
Relevant: #12

If I understand correctly, the cast button doesn't appear on the YouTube player and you have YouTube whitelisted correctly?

The input box is meant for local file URIs (or paths) for casting local media files, since the web file dialog doesn't return full paths.

**Comment by bogy1980** [comment]
Ow, i didn't get that extra button at first .. i just replaced my i5-3570K with an i7-3770 (non-K), and now the button appears... 
and it works!  (also using the button upright in the corner, that works too now!)

I guess the K series cpu was missing some features?

**Comment by hensm** [comment]
I have a 3570k in my current machine, so that’s definitely bizarre, but glad it’s working for you now.
