### ISSUE TITLE
Bridge Not Found - Node Module Error

### ISSUE THREAD

**Issue by leuchtrakete666** [hensm/fx_cast#119]
running on a Manjaro KDE 5.18

the browser console gives me this output:

[Browser_Console_cast_fx.txt](https://github.com/hensm/fx_cast/files/4776904/Browser_Console_cast_fx.txt)

**Comment by hensm** [comment]
Needs to be built with Node v12.x (rather than v14.x, I think?), since that's the latest the version `pkg` supports. Just switch it with `nvm`,

https://github.com/hensm/fx_cast/blob/9aa1cccb617ce13d08cb32c64cb5d7232decb0e3/app/bin/build.js#L198

**Comment by leuchtrakete666** [comment]
thanks. i managed to solve the problem with changing to 12.08.

but now there is another issue.
