### ISSUE TITLE
Updated translations for 'fr': French (français, langue française)

### ISSUE THREAD

**Issue by adztra** [hensm/fx_cast#123]
Hello all,
I found this extension today and I thought I'd lend a hand to translate it in French. This was my first time using GitHub so excuse me if this post wasn't necessary.

Not a developer myself so there are probably some mistakes.

**Comment by adztra** [comment]
It seems I should have exported and my work has been lost... Might try again tomorrow.

**Comment by hensm** [comment]
Ah, bad luck. Happy to take translations any time, though.
