### ISSUE TITLE
Chromecast Audio devices not supported?

### ISSUE THREAD

**Issue by ouch67** [hensm/fx_cast#129]
I've tried just the plugin, and the also plugin with the bridge, and I still get the message: "no receiver devices found".

But VLC picks it up just fine.

So are these audio only devices not yet supported? I was hoping to use it with pandora.

**Comment by hensm** [comment]
Probably #121. Should finish testing and get a release out in the next few days.

**Comment by hensm** [comment]
v0.0.7 released, will re-open if still present
