### ISSUE TITLE
Bridge immediately disconnects with empty string

### ISSUE THREAD

**Issue by hensm** [hensm/fx_cast#134]
Example log from #81:
```
fx_cast (Info): init background.js:1:1185
fx_cast (Info): init (menus) background.js:1:1185
fx_cast (Info): init (request listener) background.js:1:1185
fx_cast (Info): init (whitelist) background.js:1:1185
fx_cast (Info): init (media overlay) background.js:1:1185
fx_cast (Info): init (browser action) background.js:1:1185
fx_cast_bridge disconnected: <empty string> background.js:1:11071
fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1279
fx_cast_bridge disconnected: <empty string> background.js:1:11071
fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1279
fx_cast (Info): Cancelled receiver selection background.js:1:1185
fx_cast_bridge disconnected: <empty string> background.js:1:11071
fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1279
fx_cast_bridge disconnected: <empty string> background.js:1:11071
```

**Comment by hensm** [comment]
@outlandnish

Since I can't reproduce, would you try this test script?
https://gist.github.com/hensm/78ee532c3a04d68c28aed8b0cdaa5e87

**Comment by outlandnish** [comment]
@hensm I just tested it with both the executable in Program Files as well as with my local built version.

On the executable in Program Files, it responds with the output
```
bridge stdout 0.0.7
```

On my locally built version, I get no output to stdout. I had to make one change to your `build.js` script to allow it to work with my version of Node and that was to change the target version of Node used:
```javasccript
await pkg.exec([
        BUILD_PATH
      , "--target", `latest-${pkgPlatform[argv.platform]}-${argv.arch}`
      , "--output", path.join(BUILD_PATH, executableName[argv.platform])
    ]);
```

**Comment by outlandnish** [comment]
Oddly enough, when I go back to debugger console for the extension, I don't see that disconnect message anymore but I also don't get any receivers to show up - I have one Chromecast available

**Comment by hensm** [comment]
Discovery isn't working for some reason. I assume they can be picked up in Chrome?

<details>
<summary>My test script output</summary>

```
bridge stdout 0.0.7
bridge stdout {
  subject: 'main:/serviceUp',
  data: {
    host: '192.168.1.224',
    port: 8009,
    id: '1a260d1f845f0180259f04774d2def3f',
    friendlyName: 'Bedroom TV'
  }
}
bridge stdout {
  subject: 'main:/receiverStatus',
  data: {
    id: '1a260d1f845f0180259f04774d2def3f',
    status: { volume: [Object], application: [Object] }
  }
}
```

</details>


Discovery is thankfully not something I'm responsible for anymore, unless it's an issue with the [bindings](https://github.com/agnat/node_mdns). Bonjour comes with a CLI, so you can check which devices it's finding:
```
dns-sd -B _googlecast._tcp
```

<details>
<summary>Output</summary>

```
Browsing for _googlecast._tcp
Timestamp     A/R Flags if Domain                    Service Type              Instance Name
20:59:44.517  Add     2 33 local.                    _googlecast._tcp.         Chromecast-1a260d1f845f0180259f04774d2def3f
```

</details>


The disconnect message could be a Firefox bug if it's intermittent. I've had issues with some extension APIs randomly breaking until a restart in rare cases. All the other error cases should cause either a forwarded stderr message from the bridge or something more descriptive from Firefox itself.

**Comment by outlandnish** [comment]
@hensm I get a Chromecast discovered with the dns-sd command. I also ran a test script with the `mdns` library and it's able to discover the Chromecast

**Comment by hensm** [comment]
Weird, perhaps an issue with the custom resolver sequence? Shouldn't take effect on Windows, though.
https://github.com/hensm/fx_cast/blob/2bd9c4071f5342d5c9590f54ca11400c941eac36/app/src/bridge/index.ts#L486-L495

**Comment by outlandnish** [comment]
Potentially? I'll check it out a bit later today and get back to you on that

**Comment by outlandnish** [comment]
It doesn't appear to be the resolver code either. I copied that section verbatim into another test program and I get the service up event

**Comment by outlandnish** [comment]
I was just using my chromecast just before this so I retried the test script you provided above. Here's my new output:

```
bridge stdout 0.0.7
bridge stderr service up {
  interfaceIndex: 24,
  type: ServiceType {
    name: 'googlecast',
    protocol: 'tcp',
    subtypes: [],
    fullyQualified: true
  },
  replyDomain: 'local.',
  flags: 2,
  name: 'Chromecast-84c4933fc9b5ac654402f5a0ed75ea32',
  networkInterface: 'Wi-Fi',
  fullname: 'Chromecast-84c4933fc9b5ac654402f5a0ed75ea32._googlecast._tcp.local.',
  host: '84c4933f-c9b5-ac65-4402-f5a0ed75ea32.local.',
  port: 8009,
  rawTxtRecord: <Buffer 23 69 64 3d 38 34 63 34 39 33 33 66 63 39 62 35 61 63 36 35 34 34 30 32 66 35 61 30 65 64 37 35 65 61 33 32 23 63 64 3d 42 39 41 34 36 42 43 30 30 36 ... 120 more bytes>,
  txtRecord: {
    id: '84c4933fc9b5ac654402f5a0ed75ea32',
    cd: 'B9A46BC0065E5005B65FAB1B3B898498',
    rm: '',
    ve: '05',
    md: 'Chromecast',
    ic: '/setup/icon.png',
    fn: 'Living room',
    ca: '200709',
    st: '0',
    bs: 'FA8FCA66BE90',
    nf: '1',
    rs: ''
  },
  addresses: [ '10.20.1.122' ]
}

bridge stdout {
  subject: 'main:/serviceUp',
  data: {
    host: '10.20.1.122',
    port: 8009,
    id: '84c4933fc9b5ac654402f5a0ed75ea32',
    friendlyName: 'Living room'
  }
}
bridge stderr Assertion failed: new_time
bridge stderr  >= loop->time, file c:\pkg-fetch\precompile\node\deps\uv\src\win\core.c, line 309

bridge closed!
```

**Comment by outlandnish** [comment]
I output the `onBrowserServiceUp` event to stderr to see if it was finding the service at all and it does look like that part works. Here's the output when I did that:
```
bridge stdout 0.0.7
bridge stderr service up {
  interfaceIndex: 24,
  type: ServiceType {
    name: 'googlecast',
    protocol: 'tcp',
    subtypes: [],
    fullyQualified: true
  },
  replyDomain: 'local.',
  flags: 2,
  name: 'Chromecast-84c4933fc9b5ac654402f5a0ed75ea32',
  networkInterface: 'Wi-Fi',
  fullname: 'Chromecast-84c4933fc9b5ac654402f5a0ed75ea32._googlecast._tcp.local.',
  host: '84c4933f-c9b5-ac65-4402-f5a0ed75ea32.local.',
  port: 8009,
  rawTxtRecord: <Buffer 23 69 64 3d 38 34 63 34 39 33 33 66 63 39 62 35 61 63 36 35 34 34 30 32 66 35 61 30 65 64 37 35 65 61 33 32 23 63 64 3d 42 39 41 34 36 42 43 30 30 36 ... 120 more bytes>,
  txtRecord: {
    id: '84c4933fc9b5ac654402f5a0ed75ea32',
    cd: 'B9A46BC0065E5005B65FAB1B3B898498',
    rm: '',
    ve: '05',
    md: 'Chromecast',
    ic: '/setup/icon.png',
    fn: 'Living room',
    ca: '200709',
    st: '0',
    bs: 'FA8FCA66BE90',
    nf: '1',
    rs: ''
  },
  addresses: [ '10.20.1.122' ]
}

bridge stdout {
  subject: 'main:/serviceUp',
  data: {
    host: '10.20.1.122',
    port: 8009,
    id: '84c4933fc9b5ac654402f5a0ed75ea32',
    friendlyName: 'Living room'
  }
}
bridge stderr Assertion failed: new_time
bridge stderr  >= loop->time, file c:\pkg-fetch\precompile\node\deps\uv\src\win\core.c, line 309

bridge closed!

```

**Comment by outlandnish** [comment]
Idk if it's because I was just using my chromecast, but the device shows up now from the test script. There is an interesting error at the bottom though - I'm wondering if it has something to do with the bindings though:

```
bridge stdout 0.0.7
bridge stdout {
  subject: 'main:/serviceUp',
  data: {
    host: '10.20.1.122',
    port: 8009,
    id: '84c4933fc9b5ac654402f5a0ed75ea32',
    friendlyName: 'Living room'
  }
}
bridge stderr Assertion failed: new_time >= loop->time
bridge stderr , file c:\pkg-fetch\precompile\node\deps\uv\src\win\core.c, line 309
```

**Comment by outlandnish** [comment]
^ it looks like the above error happens specifically on my computer, an Ice lake HP Spectre x360.

A similar issue is detailed here: https://stackoverflow.com/questions/62119144/firebase-login-assertion-failed-new-time-loop-time-file-c-ws-deps-uv-src

**Comment by hensm** [comment]
Well, I won't pretend to understand why it's working now. Both the dns-sd utility and the mdns package use the same dns_sd.h C API and underlying resolver, so they _should_ have identical results.

Does it terminate after the libuv error? There's some mention of synchronizing the system clock fixing it, if that's any use. The prebuilt `pkg` binaries don't include the patched node versions yet, so that could be annoying to fix, otherwise.

**Comment by outlandnish** [comment]
Yep, it terminates with that libuv error. I've tried syncing my clock but it doesn't seem to help. It's super bizarre that it affects Ice Lake processors only

**Comment by outlandnish** [comment]
I've just tried the LTS version of Node.js and it's the same issue as on the latest version of Node. Looks like this is blocked on working with certain Ice Lake computers until there's a fix for that underlying issue

**Comment by hensm** [comment]
I assume this is causing the disconnect errors from the extension-side. As you said, not a whole lot to do here until there's a node version with a fix available. Fix is available in libuv v1.38.1, included in Node.js v14.6.0.

Latest pkg [precompiled binaries](https://github.com/vercel/pkg-fetch/releases) are at v14.4.0, updated end of June.

**Comment by outlandnish** [comment]
Yep, just confirmed it by compiling with tsc and pointing Firefox to a batch file to run the compiled code. It does show up but the option to select a Cast receiver is disabled (nor does it show in the HTML5 UI)

![screenshot](https://user-images.githubusercontent.com/1831746/89106366-d0773b80-d418-11ea-818e-1ca0ca9179c1.png)

**Comment by hensm** [comment]
The button is greyed out because screen mirroring is disabled in extension options. Best guess as to why the Netflix UI doesn't show a button is that the receiver availability state isn't being reported or the player itself hasn't loaded the new shim script and re-initialized its sender app. Try disabling/re-enabling the extension, then fully reloading the Netflix app.

**Comment by outlandnish** [comment]
I've tried reloading the pagee / disabling + re-enabling the extension. Unfortunately, it doesn't seem to do anything for it. The extension developer console doesn't seem to show any issues either. I'll take another look this evening though

**Comment by lonewitness** [comment]
Getting the same error when trying to use the extension

fx_cast (Error): Bridge connection failed and backup not enabled. background.js:1:1304
stderr output from native app fx_cast_bridge: Assertion failed: new_time >= loop->time, file c:\pkg-fetch\precompile\node\deps\uv\src\win\core.c, line 309

**Comment by outlandnish** [comment]
@lonewitness turns out that issue is related to Ice Lake processors. I think the workaround was to use a later version of Node in the installer

**Comment by lonewitness** [comment]
> @lonewitness turns out that issue is related to Ice Lake processors. I think the workaround was to use a later version of Node in the installer

Did anyone create a build with an updated node.js?

**Comment by hensm** [comment]
@lonewitness No, but you can build it yourself.

See README for more info, but provided you don't want to build your own Node.js, the particular commands should be:
```sh
npm install
npm run build
npm run install-manifest
```

The bridge will live in the `./dist/bridge` folder (you can't move it without updating the registry key).
