### ISSUE TITLE
Build fails with: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed

### ISSUE THREAD

**Issue by mwelt** [hensm/fx_cast#135]
Hi, 

second step in build instruction fails with following error message:

`npm run build`:

```
npm run build

> @ build /home/mwelt/prj/fx_cast
> npm run build:app && npm run build:ext


> @ build:app /home/mwelt/prj/fx_cast
> cd app && npm run build


> @ build /home/mwelt/prj/fx_cast/app
> node bin/build.js

> pkg@4.4.8
> Warning Failed to make bytecode node12-x64 for file /snapshot/fx_cast/app/build/main.js error (write EPIPE)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at writeOrBuffer (_stream_writable.js:399:5)
    at Socket.Writable.write (_stream_writable.js:299:11)
    at fabricate (/home/mwelt/prj/fx_cast/app/node_modules/pkg/lib-es5/fabricator.js:131:15)
    at fabricate (/home/mwelt/prj/fx_cast/app/node_modules/pkg/lib-es5/fabricator.js:144:23)
    at Socket.onError (/home/mwelt/prj/fx_cast/app/node_modules/pkg/lib-es5/fabricator.js:83:5)
    at Socket.emit (events.js:198:13)
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at onwriteError (_stream_writable.js:430:5)
    at onwrite (_stream_writable.js:461:5)
    at doWrite (_stream_writable.js:411:11)
    at writeOrBuffer (_stream_writable.js:399:5)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:198:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `node bin/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mwelt/.npm/_logs/2020-08-01T20_38_39_340Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:app: `cd app && npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mwelt/.npm/_logs/2020-08-01T20_38_39_363Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `npm run build:app && npm run build:ext`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mwelt/.npm/_logs/2020-08-01T20_38_39_383Z-debug.log

```

**Comment by hensm** [comment]
What kind of system are you building with and which version of Node are you on?

**Comment by mwelt** [comment]
> What kind of system are you building with and which version of Node are you on?

```
$ uname -a
Linux hostname 5.4.49 #1-NixOS SMP Wed Jun 24 15:50:53 UTC 2020 x86_64 GNU/Linux

$ node -v
v10.19.0

$ npm -v
6.13.4
```

**Comment by hensm** [comment]
As far as I can tell, it seems to be a NixOS-specific issue with [vercel/pkg](https://github.com/vercel/pkg), but I'm not familiar enough with it to know why. If you do figure it out, you'll also need to use Node.js v12 (`node-12_x`) or edit the [build script](https://github.com/hensm/fx_cast/blob/2bd9c4071f5342d5c9590f54ca11400c941eac36/app/bin/build.js#L196-L200) to [compile your own](https://github.com/vercel/pkg#build) `node` binary.

**Comment by hensm** [comment]
Provided you're only interested in getting a working local build, you could also just bypass pkg entirely, take the output from [tsc](https://github.com/hensm/fx_cast/blob/2bd9c4071f5342d5c9590f54ca11400c941eac36/app/bin/build.js#L114-L116) and execute it via a shell script in a custom [native manifest](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_manifests):

```json
{
    "name": "fx_cast_bridge",
    "description": "",
    "type": "stdio",
    "allowed_extensions": [ "fx_cast@matt.tf" ],
    "path": "/path/to/script.sh"
}
```

**Comment by mwelt** [comment]
Hi, 

thank you very much for your quick reply and suggestions.

I wanted to build the application, since there's no build available for NixOS in the first place, hence
a local build would be sufficient for me to work with, but unfortunately I am not a JS/node/ff-plugin dev, and, to be honest, have no idea what you suggest here :)

I completely understand that this is not the place, nor you've got to be expected to have time to describe the build process in detail, and unfortunately I have not the time to dive into JS/node development to understand your suggestion in the slightest. 

So I for now accept that this doesn't build nor run on NixOS, and close the issue. Thanks again for your efforts.

**Comment by hensm** [comment]
No problem. It could be worth taking a look at this derivation, since it appears to have a workaround:

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/unity3d/default.nix#L99-L126
