### ISSUE TITLE
[compat] Emby Media Server

### ISSUE THREAD

**Issue by agottschling** [hensm/fx_cast#138]
**App name:** Emby
**App URL:** https://app.emby.media/, Other local addresses
**App ID (if possible):** Cannot find

**Issues:**
When adding the universal web app (app.emby.media) to the whitelist, the user agent is passed and I can start casting, but media will not start playing. It will just sit in an infinite loop. This could have something to do with network settings on my end as I had a similar issue on the android app before I fixed the local subnet settings in the server, but I wanted to let you know in case there is an issue in fx_cast.

More importantly, however, I cannot add a local DNS name to the whitelist and get it to work unless I add `<all_urls>` which I'd rather not do. In my case, adding `*://mediaserver:8920/*` to the whitelist doesn't pass a chrome-based user agent and therefore the Chromecast API is never initialized. My hostname is `mediaserver` in this case, and it must be accessed on port 8920 over https. 

Any ideas? Let me know if I can provide further information or test something. 

**Error log (if applicable):**
None

**Comment by hensm** [comment]
Thanks for the report, I'll take a look at Emby in a little while.

[Match patterns](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) don't allow for specific ports, but unless I'm missing something, you should be able to add just `*://mediaserver/*` and it'll work for any port including 8920.

**Comment by agottschling** [comment]
I'll give that a shot, that was how the extension added it to the whitelist, so dunno if that needs to be addressed. 

Cheers!

**Comment by hensm** [comment]
Oh, apparently I already have. Next release. :)
e7f9968

**Comment by agottschling** [comment]
So, an update:
Changing my whitelist entry to the one you provided got me closer. The extension would pass the chrome-based user agent to the site, and I could start casting the app (both by clicking on the extension and choosing a CC from the list, and by clicking on the cast icon and choosing `Chromecast` which brought me to the previously mentioned menu). The app launches on the TV, but I cannot control it at all. Calls for media to play seem to have no effect. However, disconnecting from the CC and electing to shut down Emby on the CC will cause the app to exit and bring me back to the ambiance page. 
Hope this helps.

**Comment by hensm** [comment]
Okay, so I took a quick look, and right now, I think it's probably a web compat bug in the client where whatever component that keeps track of playback state isn't correctly reporting that to the Chromecast component. It's Chrome-specific code, so it wouldn't be too surprising.

It doesn't actually use much of the Chromecast API itself, just sets up a messaging connection and does its own thing, so there's not much else to go wrong.

I'll keep digging later when I've got some more time and see if I can come up with a workaround.

**Comment by hensm** [comment]
My fault after all, seems to be fully working now. Will be fixed in the next release.

**Comment by agottschling** [comment]
You're a legend man! I'm guessing I just have to wait for the next release to get the fix?

**Comment by hensm** [comment]
Either that, or you could build your own version in the meantime. Should have something by the end of the week.
