### ISSUE TITLE
Bridge Issue with version 0.1.0 Win x64

### ISSUE THREAD

**Issue by tyler274** [hensm/fx_cast#146]
On latest Windows and Firefox. Updated to version 0.1.0 of the extension and x64 bridge (which reports 0.7.0 to running with ```--version```, I double checked its the product 0.1.0 installer though). Extension option page reports bridge issue, and daemon mode didn't seem to change anything (unless I need to add a firewall rule manually).

Can't cast, though the chromecasts on my network are discovered.

**Comment by hensm** [comment]
Yeah, the version string is incorrect (see #142). Daemon mode is only for running the bridge on another machine or from within a sandboxed environment like Snap.

I can't reproduce this issue, but if you're getting the bridge issue error on the options page, there should be an error in the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console). Some more info about your particular setup could be helpful too.

**Comment by hensm** [comment]
Probably #147
