### ISSUE TITLE
Allow adding known apps to whitelist from the options page

### ISSUE THREAD

**Issue by hensm** [hensm/fx_cast#150]
Should be able to add known app match patterns to the whitelist via a dropdown (or similar) method. 

https://github.com/hensm/fx_cast/blob/05ff30196442cef15191125d260025142943ff7b/ext/src/lib/knownApps.ts#L18-L27

**Comment by jorgenboganes** [comment]
Is this issue still relevant? If so, I'll have a go at it.

**Comment by hensm** [comment]
Yep, it's still relevant. Feel free.
