### ISSUE TITLE
this's site app (not found)

### ISSUE THREAD

**Issue by feiticeir0** [hensm/fx_cast#152]
I'm unable to cast Netflix (or Disney+) to my Chromecast device. 
I was able before, but now, I just get the cast window , were it shows my Chromecast device, but the cast button is disabled and in the cast dropdown I get:

Cast this site's app (not found)

I did tried on Linux (first) and then on Windows.. No success on both...  Latest firefox, latest fx_cast extension and bridge...

What could it be ?

**Comment by hensm** [comment]
You need to cast from the player UI, not the toolbar button. Check the whitelist if it's not appearing.

**Comment by feiticeir0** [comment]
Thanks for the reply, but I don't know what do you mean.  What player UI ? Netflix or Disney+ are playing from a browser TAB, and when on that TAB, I press the fx_cast button in the addons section... Here's a screenshot of the button
![fx_cast](https://user-images.githubusercontent.com/2813722/93685542-009d9b00-faa8-11ea-9a0c-7d6a2ccf63cc.png)

**Comment by hensm** [comment]
Yeah, provided they're on the whitelist (see options page), the cast button you need to use would show in the site's player UI toolbar, usually next to the full screen button.

If they're not showing up and the sites are definitely on the whitelist, see if there are any relevant logs (see CONTRIBUTING at this repository's root).

I probably won't be able to help much right now, since I don't currently have access to my Chromecast.

**Comment by nathanph** [comment]
> Thanks for the reply, but I don't know what do you mean. What player UI ? Netflix or Disney+ are playing from a browser TAB, and when on that TAB, I press the fx_cast button in the addons section... Here's a screenshot of the button

FYI, @feiticeir0, in case it wasn't clear, try right-clicking the the extension icon.

![image](https://user-images.githubusercontent.com/6075916/98133936-30540700-1e8c-11eb-8d1c-c8112fccafa5.png)

**Comment by feiticeir0** [comment]
Hi ! 
All that it's done and added... I know now what @hensm was talking about when the cast button should appear on the video controls... It appears, but not all.. Just some ! But I'm happy with it ! Thank you
