### ISSUE TITLE
bridge process does not terminate

### ISSUE THREAD

**Issue by demokritos** [hensm/fx_cast#164]
The bridge process started by fx_cast_bridge.sh does not terminate when Firefox is shut down.

https://github.com/hensm/fx_cast/blob/5a9a32f5ab0db1dd77abd47c738797de9c0b0b21/app/bin/build.js#L165

I  found out the `exec` is helpful.

```bash
NODE_PATH="${modulesDir}" exec node $(dirname $0)/src/main.js --__name $(basename $0) "$@"
```

**Comment by hensm** [comment]
Sorry for the late response.

Will try to test it out on Linux, since it's working fine on macOS. Pretty far along on the replacement bridge, so I may just focus on that since there won't be another release with this bridge.
