### ISSUE TITLE
With fx_cast extension installed, Youtube makes my comments invisible

### ISSUE THREAD

**Issue by demokritos** [hensm/fx_cast#186]
**OS version:** Arch Linux
**Browser version:** Firefox 89.0.2, 90.0b12, 91.0a1
**Extension version:** 0.1.2
**Bridge version:** 0.1.0

**Description**
If Youtube URL is included in the whitelist, my comments posted afterward are made invisible by Youtube (maybe for spam).
Also if I try seeing my comments in 'Your data in Youtube', it says "Your browser version isn't supported anymore."

![Screenshot 2021-07-10 at 13-37-23 Google - My Activity](https://user-images.githubusercontent.com/3399860/125152486-d082ce00-e187-11eb-876a-61b70942aa79.png)

**Steps to reproduce**
1. Go to Youtube
2. Add Youtube URL to Whitelist
3. View some video and post a comment
4. refresh that page and find that comment

**Expected behaviour**
The posted comment should be there.

**Comment by hensm** [comment]
Yeah, presumably some type of spam prevention. If YouTube is whitelisted, it'll use a nonstandard hybrid Chrome/Firefox user agent string which was the only reliable way I could get it to work.

Unless they've stopped shipping Chrome-specific code with Firefox polyfills, I'm not sure much can be done.
