### ISSUE TITLE
"No receiver devices found" but chrome can cast

### ISSUE THREAD

**Issue by F43nd1r** [hensm/fx_cast#192]
**OS version:** Windows 10
**Browser version:** Firefox 93.0
**Extension version:** 0.1.2
**Bridge version:** 0.1.0

**Description**
FX_cast doesn't find my chromecast, always shows "No receiver devices found". Chrome on the same device can cast without issues.

**Steps to reproduce**
1. Install Bridge and extension
2. try to cast anything

**Expected behaviour**
Receiver is detected

**Logs**
I can't find anything relevant in any of the log locations. Here's the everything in the extension log:
```
fx_cast (Info): init background.js:1:1201
fx_cast (Info): checking for bridge... background.js:1:1201
Unknown localization message sync failed
---------------------
invalid token: google icon-manager.js:80
fx_cast (Info): ... bridge compatible! background.js:1:1201
fx_cast (Info): init (menus) background.js:1:1201
fx_cast (Info): init (whitelist) background.js:1:1201
fx_cast (Info): init (media overlay) background.js:1:1201
fx_cast (Info): init (browser action) background.js:1:1201
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page.
```

**Comment by TheOncomingStorm** [comment]
I'm having the same issue but I'm early in the troubleshooting process. Have you had any luck so far?

**Comment by F43nd1r** [comment]
Unfortunately not. I'm now using my phone as primary casting source.

**Comment by Robert-Ernst** [comment]
Same situation here on mac

**Comment by Savke** [comment]
Same situation on Ubuntu 20.04

**Comment by hensm** [comment]
Closing with #199.
