### ISSUE TITLE
when fx_cast is enabled maxstream won't work anymore

### ISSUE THREAD

**Issue by dylantrevor87** [hensm/fx_cast#205]
**OS version:** windows10
**Browser version:** 100
**Extension version:** 0.2.0-alpha
**Bridge version:** 0.2.0-alpha

**Description**
Hello, when fx_cast extension is enabled the streaming site maxstream won't play videos.
I'm not talking about casting, just normally playing in the page. 
fx_cast is interfering with the normal functionality of the page.
If I disable fx_cast then the videos are played correctly,

**Steps to reproduce**
1. Please install fx_cast 0.2.0
2. load any page from maxstream, like for example:   https://maxstream.video/xqda7cebwflh/c3V4eWlYTmx3eXI3djZ5YTRQTGc3Zz09
3. try to play the video by clicking the play button in the video (close any popup pages or before the test install ublock origin)

**Expected behaviour**
the video should play into the page (not casted)
**Logs**
Provide any applicable logs here. Info on where to find them is located [here](https://github.com/hensm/fx_cast/blob/master/CONTRIBUTING.md#bug-reports).

**Comment by hensm** [comment]
Will be fixed in the next release
