### ISSUE TITLE
"No receiver devices found"

### ISSUE THREAD

**Issue by SuperSonicHub1** [hensm/fx_cast#212]
**OS version: Ubuntu 20.04.4 LTS (Focal Fossa)**
**Browser version: Firefox 99.0**
**Extension version: 0.2.0**
**Bridge version: 0.2.0**

**Description**
The extension cannot find the single Chromecast on my home network. My desktop computer is connected to the network over Ethernet. My phone, which is connected over WiFi, is able to cast its screen to the Chromecast from the Google Home app. I've verified that my desktop and phone are on the same network by hosting a web server on the former and accessing it from the latter's web browser.

**Steps to reproduce**
1. Go to https://www.youtube.com/watch?v=W43aQxzjyeM
2. Click on "Cast" option in context menu
3. See "No receiver devices found" message

**Expected behaviour**
1. Go to https://www.youtube.com/watch?v=W43aQxzjyeM
2. Click on "Cast" option in context menu
3. See Chromecast called "Living Room TV"

**Logs**
```
fx_cast (Info): init background.js:1:1778
fx_cast (Info): checking for bridge... background.js:1:1778
fx_cast (Info): ... bridge compatible! background.js:1:1778
fx_cast (Info): init (menus) background.js:1:1778
fx_cast (Info): init (whitelist) background.js:1:1778
fx_cast (Log): Reference window missing positional properties. background.js:1:1697
fx_cast (Info): Cancelled receiver selection background.js:1:1778
fx_cast (Log): Reference window missing positional properties. background.js:1:1697
fx_cast (Info): Cancelled receiver selection background.js:1:1778
fx_cast (Log): Reference window missing positional properties. background.js:1:1697
fx_cast (Info): Cancelled receiver selection background.js:1:1778
```

I really hope this isn't a dupe. Looked at all the other "no devices" issues and considered them too old to be relevant.

**Comment by hensm** [comment]
What's Avahi reporting (if anything)?
```sh
$ avahi-browse _googlecast._tcp
```

If you can run this test script, that would also be helpful:
[mdns_test.zip](https://github.com/hensm/fx_cast/files/8546305/mdns_test.zip)

Probably has the same dependencies as listed [here](https://github.com/hensm/fx_cast#debian--ubuntu).

**Comment by SuperSonicHub1** [comment]
> What's Avahi reporting (if anything)?
After running the given command, nothing is written to standard output? What *should* be happening?

> If you can run this test script, that would also be helpful:
[mdns_test.zip](https://github.com/hensm/fx_cast/files/8546305/mdns_test.zip)
After running the script I get this output:
```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/blog/projects/avahi-compat.html>
Local addresses [
  '192.168.2.189',
  '192.168.250.1',
  '201:c830:2061:f8a6:95b5:c45a:b670:245'
]
```
After that the program hangs and does nothing. Again, is something more meant to happen?

**Comment by hensm** [comment]
For whatever reason, Avahi isn't able to discover any chromecast devices. The output should be some info about the discovered devices.

In any case, this isn't an fx_cast issue, so all I can suggest is that you check your setup.

- Is Avahi configured properly? Should be fine out of the box on Ubuntu, but worth checking.
- Anything that would be blocking mDNS traffic (firewall rules, network configuration, VM etc.)?

Maybe try Ask Ubuntu or Unix SE for more specific advice.
