### ISSUE TITLE
Daemon configuration service file path fix and info for Firefox Flatpak

### ISSUE THREAD

**Issue by luca-demma** [hensm/fx_cast#225]
In the daemon configuration readme is written to create a file in 
`/etc/systemd/fx_cast.service`
I think it should be in 
`/etc/systemd/system/fx_cast.service`
otherwise the systemctl command fails because it doesn't find the file (tested on Pop_OS (ubuntu based) )

Another improvement IMO would be to add in the homepage the same info about the firefox snap package for the Flatpak package that suffers of the same problem

**Comment by hensm** [comment]
Fixed, thanks.
