### ISSUE TITLE
Windows installer

### ISSUE THREAD

**Issue by hensm** [hensm/fx_cast#24]
Re #4 

Options:
* WiX (in wine for macOS/Linux)
  http://wixtoolset.org/
* NSIS
  https://nsis.sourceforge.io/Main_Page

**Comment by Smultie** [comment]
Any reason you don't build the Windows installer?

**Comment by hensm** [comment]
There isn't one yet. It works on Windows, and there's an install script for development, but if I released a binary, you'd need to manually create registry keys to get Firefox to find it.

I'll write the installer when I get access to my Windows machine. Or I might try on macOS and see how it goes.

**Comment by Smultie** [comment]
Ah, right. That was my first thought "Maybe he doesn't run Windows"
Makes sense! 
Very promising whatsoever, very much looking forward to a working casting experience on Firefox!

**Comment by hiya-tiger** [comment]
>"I'll write the installer when I get access to my Windows machine. "

Time to get a VM solution?

**Comment by hensm** [comment]
> Time to get a VM solution?

That would probably just about fill up the rest of my drive. The part for my PC arrives tomorrow, and with my internet speed, I think the postal system would beat the ISO download.

**Comment by renegade2k** [comment]
Just a suggestion for improvement:

> Install the Firefox extension and companion bridge application. Downloads can be found on the website or in the GitHub releases section.
macOS/**Windows versions have installers**, ...

Maybe correct this, like "MacOS version has an installer, Windows version will come later",
so the project does not look like clickbait for Windows users.

**Comment by hensm** [comment]
1f144e4 — Basic NSIS installer
