### ISSUE TITLE
Bridge issue connection timed out

### ISSUE THREAD

**Issue by Evoden1** [hensm/fx_cast#241]
**OS version:Windows 11 22H2 Build 22621.521**
**Browser version:Firefox 106.0b9 (64-bit) BETA**
**Extension version:0.3.1**
**Bridge version:0.3.0**

**Description**
When i click on the extension icon it shows "There is a problem with the bridge!" then it takes me to the options of the extension where it says "Bridge issue connection timed out" Also i have installed both Bonjour SDK for Windows and NSIS

**Steps to reproduce**
1. Click on the extension icon 
2. Then it shows "There is a problem with the bridge!"
![image](https://user-images.githubusercontent.com/95939609/194752570-1aa341fe-9bb8-4482-b2a9-f886c06e6fdb.png)

**Expected behaviour**
To show devices that i can connect to

**Logs**
stderr output from native app fx_cast_bridge: Unexpected result while probing for avahi: Error: dns service error: service not running
stderr output from native app fx_cast_bridge:     at supportsInterfaceIndexLocalOnly (C:\snapshot\app\node_modules\mdns\lib\avahi.js:17:12)
stderr output from native app fx_cast_bridge:     at Object.<anonymous> (C:\snapshot\app\node_modules\mdns\lib\avahi.js:34:20)
stderr output from native app fx_cast_bridge:     at Module._compile (pkg/prelude/bootstrap.js:1887:22)
stderr output from native app fx_cast_bridge:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
stderr output from native app fx_cast_bridge:     at Module.load (node:internal/modules/cjs/loader:981:32)
stderr output from native app fx_cast_bridge:     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
stderr output from native app fx_cast_bridge:     at Module.require (node:internal/modules/cjs/loader:1005:19)
stderr output from native app fx_cast_bridge:     at Module.require (pkg/prelude/bootstrap.js:1812:31)
stderr output from native app fx_cast_bridge:     at require (node:internal/modules/cjs/helpers:102:18)
stderr output from native app fx_cast_bridge:     at Object.<anonymous> (C:\snapshot\app\node_modules\mdns\lib\mdns.js:31:19) {
stderr output from native app fx_cast_bridge:   errorCode: -65563
stderr output from native app fx_cast_bridge: }

**Comment by hensm** [comment]
Is this a custom build? You installed the Bonjour SDK, but is Bonjour itself actually installed and running?
Try: `dns-sd -B _googlecast._tcp`

**Comment by Evoden1** [comment]
What do you mean by a custom build? I ran the command in CMD
> Browsing for _googlecast._tcp
> DNSService call failed -65563

**Comment by hensm** [comment]
I mean is it a release build or did you build it yourself? Bonjour SDK and NSIS are build dependencies, and runtime dependencies are bundled with the installer, so I'm just checking.

Looks like Bonjour isn't working.

Check that it's installed, and if not you can find the installer package at:
`C:\Program Files\Bonjour SDK\Installer\Bonjour64.msi`

![arp](https://user-images.githubusercontent.com/6956633/194758024-be19618d-8e78-4d4a-a4ba-13c96cfd86f3.png)

**Comment by Evoden1** [comment]
Now it's working, i clicked on the installer at
`C:\Program Files\Bonjour SDK\Installer\Bonjour64.msi`
Thank you

**Comment by Evoden1** [comment]
It's Firefox beta release
