### ISSUE TITLE
No bridge found - There is a problem with the bridge

### ISSUE THREAD

**Issue by cboin1996** [hensm/fx_cast#242]
**OS version:**
```
   /ssssssssssshdmmNNmmyNMMMMhssssss/      OS: Ubuntu 22.04.1 LTS x86_64                                                                                     
  +ssssssssshmydMMMMMMMNddddyssssssss+     Host: MS-7B50 1.0                                                                                                 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Kernel: 5.15.0-52-generic                                                                                         
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Uptime: 9 hours, 5 mins 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Packages: 2795 (dpkg), 12 (snap) 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Shell: zsh 5.8.1 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   Resolution: 1920x1080, 2560x1440 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 42.4 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   WM: Mutter 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    WM Theme: Yaru-blue-dark 
  +sssssssssdmydMMMMMMMMddddyssssssss+     Theme: Yaru-blue-dark [GTK2/3] 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      Icons: Yaru-blue-dark [GTK2/3] 
    .ossssssssssssssssssdMMMNysssso.       Terminal: tmux 
      -+sssssssssssssssssyyyssss+-         CPU: Intel i7-9700K (8) @ 4.900GHz 
        `:+ssssssssssssssssss+:`           GPU: NVIDIA GeForce RTX 2080 Rev. A
            .-/+oossssoo+/-.               Memory: 10029MiB / 64249MiB 
```
**Browser version:**
Firefox 106.0 (64-bit)

**Extension version:**
0.3.1
**Bridge version:**
0.3.0

**Description**
Cannot cast, says `There is a problem with the bridge!`

Output of `avahi-browse -rv _googlecast._tcp`:
```bash
E Ifce Prot Name                                          Type                 Domain
+   eno2 IPv4 Chromecast-63e9847553a877d3e71d02487336317a   _googlecast._tcp     local
=   eno2 IPv4 Chromecast-63e9847553a877d3e71d02487336317a   _googlecast._tcp     local
   hostname = [63e98475-53a8-77d3-e71d-02487336317a.local]
   address = [192.168.2.14]
   port = [8009]
   txt = ["rs=YouTube" "nf=1" "bs=FA8FCA3146A3" "st=1" "ca=201221" "fn=Den TV" "ic=/setup/icon.png" "md=Chromecast" "ve=05" "rm=" "cd=938C11E78F9DF043D35DFECE4E4B76C7" "id=63e9847553a877d3e71d02487336317a"]
: Cache exhausted
: All for now
```

**Steps to reproduce**
1. Install the extension (v0.3.1)
2. Install debian package for bridge
3. Try to cast

**Expected behaviour**
Casting should be available I would think. Maybe I missed something in the install, but I could not figure it out.

**Comment by hensm** [comment]
Presumably you're using the snap version of Firefox, since you're on Ubuntu. It doesn't work with native messaging, so you need to either use the [bridge daemon](https://github.com/hensm/fx_cast/wiki/daemon) (in which case for now you should install [this](https://github.com/hensm/fx_cast/issues/230#issuecomment-1251659577) version of the bridge after uninstalling the existing one), or install a non-snap version of Firefox and it should work without issue.

There's an FAQ entry on the site about this, but I've just noticed there's nothing in the README, so I'll add something to clear it up a little.

**Comment by cboin1996** [comment]
@hensm Thank you so much.

I followed this tutorial: https://www.omgubuntu.co.uk/2022/04/how-to-install-firefox-deb-apt-ubuntu-22-04 to install non-snap firefox.
I then installed `v0.3.1` extension, and everything worked immediately (including mirroring!).
