### ISSUE TITLE
Unable to cast from YouTube/All4 - Google speakers are greyed out

### ISSUE THREAD

**Issue by jed84** [hensm/fx_cast#243]
**OS version:** Win 11 22H2
**Browser version:** 106.0.1 (64-bit)
**Extension version:** 0.3.1
**Bridge version:**  0.3.0
**User agent:** "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/104.0.0.0 Gecko/20100101 Firefox/103.0"

**Description**
The extension can successfully pull up a list of compatible devices when attempting to cast video from Firefox to Google Home/Nest speakers. However, it's impossible to connect with the device when visiting YouTube/All4. Right-clicking on a device gives the option to cast to that device, but it is also greyed out.

![obraz](https://user-images.githubusercontent.com/47121522/197359839-d2db5bd0-6ed9-4b14-bb6e-8a555219fbef.png)

**Steps to reproduce**
    Open a YouTube video in Firefox
    Click the icon for the fx_cast extension in the toolbar.
    Attempt to select a device to cast to.

**Expected behaviour**
After opening a video in Firefox and launching YouTube/All4, I expect to be able to select the device and start casting the video.

**Notes**
The extension works correctly when streaming from Spotify.

Logs
Provide any applicable logs [here](https://github.com/hensm/fx_cast/blob/master/CONTRIBUTING.md#bug-reports). Info on where to find them is located here.

**Comment by hensm** [comment]
Ah, speakers, that makes sense. Chromecast apps have a compatibility flag for audio-only devices that the extension checks before it allows you to cast to them. Spotify supports them, YouTube and All 4 do not.

I can't say whether it would actually work if you could cast to them, they're certainly not supposed to receive video streams. The difference is that Chrome can capture an audio stream from a tab and send that via its mirroring functionality whereas Firefox [doesn't have API support for that yet](https://bugzilla.mozilla.org/show_bug.cgi?id=1541425).

So, this is the intended behaviour, but there's clearly some room for improvement in the UI as to how unsupported devices should be displayed (if at all).

**Comment by jed84** [comment]
Thank you so much for explaining this.

Hopefully, it can be fixed at some point by firefox (not much hope tho, considering the development of the app).

**Comment by hensm** [comment]
You're welcome.

> not much hope tho, considering the development of the app

Yeah, I'm certainly not getting my hopes up. I've been waiting 4-5 years for improvements on a number of things on the Firefox side that have yet to materialise. Limited development resources, I suppose.
