### ISSUE TITLE
Support for Roku?

### ISSUE THREAD

**Issue by SevilleCode** [hensm/fx_cast#245]
**OS version:**
Windows 10
**Browser version:**
Firefox 106.0.1
**Extension version:**
v0.3.1
**Bridge version:**
v0.3.0

**Description**
I cannot cast YouTube videos to my Roku Express from Firefox. It says it cannot find any supported devices. Casting works normally in Chromium browsers, so it's probably something particular to this extension.

**Steps to reproduce**
1. Click casting button in Firefox while watching a YouTube video.
2. Window says, "Cast YouTube to" but doesn't provide a list of players. Sometimes there is an error message about not being able to find a supported player.

**Expected behaviour**
Expected to see the Roku Express listed as an option, which I can then select and watch YouTube on the tv.

Thank you!

**Comment by hensm** [comment]
There's currently no DIAL support (#7), which is what Roku uses for casting YouTube/Netflix. It'll only work on actual Chromecast-supported devices.

**Comment by SevilleCode** [comment]
Okay, thank you for the explanation.
