### ISSUE TITLE
Casting in Mirror Mode does not send audio

### ISSUE THREAD

**Issue by Aegor1998** [hensm/fx_cast#247]
OS version: PopOS 22.04
Browser version: Firefox 106.0.3
Extension version: 0.3.1
Bridge version:  0.3.0

**Description**
I was trying to get fx_cast to cast a video from gogoanime.tel I had to enable screen mirroring because it wouldn't pick up the stream otherwise. I got the video to stream, but It is not passing audio to the casted device.

**Steps to reproduce**
1. Go to about:addons
2. Go to Extensions > fx_cast > Preferences > Show advanced options > Screen mirroring
3. Enable screen mirroring
4. Go to gogoanime.tel and selected a video
5. Cast to the  a device
6. Sound should be coming out of a device the media is on, and not the casted to device

**Expected behavior**
Some documented way to pass audio over to the casted device.

**Logs**
No logs applicable

**Comment by hensm** [comment]
This is a known issue with screen mirroring.
https://hensm.github.io/fx_cast/#Why_is_there_no_sound_when_casting_a_screen_or_tab?

Though, I'm able to get that site to work by whitelisting `https://gogohd.net/*`.
