### ISSUE TITLE
Cannot scroll/filter device-selection list

### ISSUE THREAD

**Issue by petemounce** [hensm/fx_cast#248]
**OS version:** ubuntu 22.04 LTS
**Browser version:** firefox 106.05
**Extension version:** 0.3.1
**Bridge version:** 0.3.0

**Description**
I'm in a 27-floor hotel with around 30 rooms per floor and a smart TV with a chromecast in every room.

Sadly, my room's TV does not appear in the "above the fold" area of the list that the firefox extension renders for me.

**Steps to reproduce**
1. Choose a modern hotel with Smart TVs
2. Check in
3. Observe list is not scrollable/filterable

**Expected behaviour**
It would be lovely to be able to either scroll the (alpha-sorted) list, or fuzzy-find by typing in it to get my room's TV

**Logs**

**Comment by hensm** [comment]
f759d3b, added for next release.
![filter](https://user-images.githubusercontent.com/6956633/202876476-2dec44aa-cc6d-43f4-a8d7-e224557e5c5b.png)

**Comment by petemounce** [comment]
Thanks!
