### ISSUE TITLE
RPM Fails to Install on Fedora 28 and 29

### ISSUE THREAD

**Issue by fruzyna** [hensm/fx_cast#25]
When installing as described in the README
> Transaction check error: package fx_cast_bridge-0.0.1-1.x86_64 is intended for a different operating system

**Comment by hensm** [comment]
It's cross-built from darwin and it looks like I forgot to specify the target. Does this one work?
[fx_cast_bridge-0.0.1-1.x86_64.rpm.zip](https://github.com/hensm/fx_cast/files/2792256/fx_cast_bridge-0.0.1-1.x86_64.rpm.zip)

**Comment by mail929** [comment]
It successfully installed this time, however, the add-on reports that the bridge is not found. Is there anyway to check if it is running?

**Comment by hensm** [comment]
This is the generated spec file. I haven't tested it, so just double check those paths.

````specfile
Name: fx_cast_bridge
Summary: fx_cast_bridge
Version: 0.0.1
Release: 1
License: MIT

%description
fx_cast_bridge

%install
rm -rf $RPM_BUILD_ROOT
mkdir -p $RPM_BUILD_ROOT//opt/fx_cast/ \
         $RPM_BUILD_ROOT//usr/lib/mozilla/native-messaging-hosts/

cp %{_distdir}/bridge $RPM_BUILD_ROOT//opt/fx_cast/
cp %{_distdir}/fx_cast_bridge.json $RPM_BUILD_ROOT//usr/lib/mozilla/native-messaging-hosts/

%files
/opt/fx_cast//bridge
/usr/lib/mozilla/native-messaging-hosts//fx_cast_bridge.json

````

**Comment by mail929** [comment]
All the files appear to be properly in place

**Comment by hensm** [comment]
Should be an error in the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) if it's reporting as not found.

**Comment by mail929** [comment]
All I found was:
> No such native application fx_cast_bridge NativeMessaging.jsm:99
	NativeApp</this.startupPromise< resource://gre/modules/NativeMessaging.jsm:99:9

**Comment by hensm** [comment]
That would suggest the wrong manifest location. Copy `fx_cast_bridge.json` to `/usr/lib64/mozilla/native-messaging-hosts/` and see if it picks it up.

**Comment by mail929** [comment]
Bridge found!
