### ISSUE TITLE
*.deb package missing maintainer field

### ISSUE THREAD

**Issue by Batcastle** [hensm/fx_cast#27]
When the *.deb package is installed, if the user does ANYTHING with apt/dpkg through the command line, dkpg throws this error:

```
dpkg-query: warning: parsing file '/var/lib/dpkg/status' near line 53457 package 'fx-cast-bridge':
 missing maintainer
```
If the *.deb package is built using some sort of helper tool such as Debreate then this should be easy to fix. If this is being built in a more manual method then it may be more involved.

**Comment by hensm** [comment]
#26 fixed this, just haven't submitted a new release yet.
