### ISSUE TITLE
Some way to remove the fx_cast bridge from macOS?

### ISSUE THREAD

**Issue by impreza233** [hensm/fx_cast#29]
I don't find any way to remove the bridge in macOS.

**Comment by impreza233** [comment]
I don't find any way to remove the bridge in macOS.

**Comment by hensm** [comment]
Delete:
`/Library/Application Support/fx_cast/bridge`  
`/Library/Application Support/Mozilla/NativeMessagingHosts/fx_cast_bridge.json`

**Comment by impreza233** [comment]
Thanks. It worked!!

**Comment by dnkm** [comment]
thanks!
