### ISSUE TITLE
Make a Firefox mobile version!

### ISSUE THREAD

**Issue by TheRealFame** [hensm/fx_cast#305]
Hello, This is one question I've really wanted to ask! Since Firefox on mobile has no casting. Can there be mobile support in a future update?

**Comment by hensm** [comment]
This came up recently (#302), and you can read the response I left on that issue, but the gist is that it's a nontrivial amount of work that I just don't have time to do right now (though I'm happy to collaborate with anyone who's interested in getting it working).

**Comment by TheRealFame** [comment]
I see then, Hopefully it comes around someday!
