### ISSUE TITLE
Doesn't seem to work on Mac?

### ISSUE THREAD

**Issue by April93** [hensm/fx_cast#31]
I installed the bridge, as well as the extension. But it never seems able to actually cast. No cast button appears on any media, and trying to use the toolbar button never populates the list of chromecast devices, nor can I ever enable casting.

I tried fiddling with the various addon options but nothing seems to help. What am I doing wrong?

**Comment by hensm** [comment]
Bridge section on the options page should look like this:
https://i.imgur.com/fl3RHij.png

The toolbar button doesn't do anything yet. Cast buttons *should* appear on sites that are whitelisted, though compatibility is patchy and Netflix is the only one I've done any proper testing for.

At the very least, media casting should work via the "Cast..." context menu item on video or audio elements. Or tab casting, if that's enabled.

**Comment by April93** [comment]
Yeah that's how it looks on mine. There's no button, and right-clicking stuff doesn't bring up a cast option either. Netflix is the site I was trying, as suggested, but nothing ever came up.

**Comment by hensm** [comment]
What's the console output when you run this (index.html in browser)?
[casttest.zip](https://github.com/hensm/fx_cast/files/2942549/casttest.zip)

**Comment by April93** [comment]
Okay that seems to work fine. The button appears on a black background, when I click it it pulls up my chromecast properly. And then I can click cast, and it'll begin casting, and then the chromecast changes into a black screen with the blue cast icon on it. So it seems to have worked. As I said the issue has always been not having anything to click to pop up the casting option. Since the button is there, I could bring it up. The toolbar thing still shows nothing, as usual.

The console output is a bit long, looks like it was successful though? Do you want me to still post it?

**Comment by hensm** [comment]
No need to post the log if it worked.

Most custom players hide the native controls and context menu. Some sort of media picker that lists everything on the page is what I had in mind to solve that, but nothing implemented as of yet.

If the test page works, Netflix should also work. Though, the test page always shows a cast button, Netflix loads it in once the `__onGCastApiAvailable` handler is called. So, possibly some issue with that. It's a bit temperamental, especially in certain network conditions. Hard to say exactly what would be causing it, but checking the page/browser console, whitelist entries, etc... is a good shout.

Stopping a cast session is possible if you set it to stop when the tab closes. Apps usually have their own way of stopping it. Plan is to put all this stuff in the toolbar popup, similar to the way Chrome does it (#10).
