### ISSUE TITLE
Windows bridge installer doesn't automatically run as administrator

### ISSUE THREAD

**Issue by pmdevita** [hensm/fx_cast#34]
I'm not sure if this is because SmartScreen tried to block the .exe but the installer doesn't automatically try to run as administrator, which makes the install fail since it doesn't have the permissions to write the files to the Program Files directory. Manually running the .exe as admin works fine though.

**Comment by hensm** [comment]
Yeah, my mistake on that one, was testing mostly in Wine, which didn’t have a problem with it.

285b31e fixed it.

I’ll leave the issue open till I upload a new installer.
