### ISSUE TITLE
Add a Icon

### ISSUE THREAD

**Issue by jcc10** [hensm/fx_cast#35]
Could we get an actual icon for the extension? Possibly even with the letter Beta  on it to show that it's in beta status.

Not really "critical", but it would be nice to have a actual icon.

Technically there should be four modes:

  A   Unavailable: While Cast receivers are not available, the Cast button does not appear. (Probably easier to make the icon red or with an X instead of the cast waves. Useful to show that there is nothing to cast to.)
  B   Disconnected: While Cast receivers are available, the Cast button appears. (Normal default behavior, probably all we really need right now.)
  C   Connecting: While the Cast receiver is connecting, the Cast button animates the waves in the icon progressively. (Not essential at this stage but should be planned for)
  D   Connected: While this app is connected to the Cast receiver, its Cast button appears with a filled frame shape. (Again not required at this stage but should be planned for)

**Comment by hensm** [comment]
Sounds good.

I'm not 100% sure what the licensing rules are regarding the official cast icons though, especially since I'd need to modify them to fit with the Firefox theme. I'll probably just recreate them from scratch.

**Comment by hensm** [comment]
First draft:

![Screenshot 2019-03-11 at 05 29 41](https://user-images.githubusercontent.com/6956633/54102088-d6512480-43be-11e9-8be8-b5ddc39bbd66.png)
![Screenshot 2019-03-11 at 05 18 08](https://user-images.githubusercontent.com/6956633/54101882-d4d32c80-43bd-11e9-88f3-2898252afbe2.png)
![Screenshot 2019-03-11 at 05 18 59](https://user-images.githubusercontent.com/6956633/54101881-d4d32c80-43bd-11e9-9829-37433629f838.png)

Not too keen on the unavailable icon, it's not very clear that it's a cast icon still. Might just disable the browser action and rely on the opacity change.

**Comment by bhargavgv** [comment]
You can just put a slash through the icon when it's deactivated. Like this one:
![icon](https://user-images.githubusercontent.com/25331232/54228935-96cb2b00-44d9-11e9-85f7-fdfecedca6b9.png)
(From https://materialdesignicons.com/)

**Comment by hensm** [comment]
Same problem as with the connecting icon in that there's no way to set a theme-specific icon. Besides, I think the dimmed, disabled icon for the unavailable state fits more with the Firefox style.

![Screenshot 2019-03-13 at 09 36 33](https://user-images.githubusercontent.com/6956633/54268616-81a2da80-4573-11e9-8fba-c0b36ea98ca1.png)
