### ISSUE TITLE
pop-up overflow

### ISSUE THREAD

**Issue by eboye** [hensm/fx_cast#36]
I can't find this issue already reported, so if it's already reported, please correct me.

On the FF 66.0b14 (Dev Edition) on MacOS 10.14.3 I've got this popup:

![image](https://user-images.githubusercontent.com/624357/54165550-752e5d00-4461-11e9-8d59-5604377d9e84.png)

I see in other screenshots that it's not supposed to be like that. So what could be wrong?

**Comment by hensm** [comment]
The toolbar button doesn't do anything yet, it's just a placeholder. Originally, that was going to be the cast selection popup, but the `openPopup` API can only be called from a user action handler, so it opens in a separate window instead.
