### ISSUE TITLE
[compat] Spotify

### ISSUE THREAD

**Issue by hensm** [hensm/fx_cast#38]
**App name:** Spotify
**App URL:** https://open.spotify.com/
**App ID (if possible):** CC32E753

**Issues:**
Uses the `cast.framework` API, which isn't yet implemented (#3).

**Error log (if applicable):**
````
Loading failed for the <script> with source “https://www.gstatic.com/cv/js/sender/v1/cast_sender.js?loadCastFramework=1”.  featured:1:1
````

**Comment by fallaciousreasoning** [comment]
Note: This seems to be working for me (if I whitelist Spotify).
