### ISSUE TITLE
README Installation Guide Typo

### ISSUE THREAD

**Issue by parcar** [hensm/fx_cast#45]
Suggested fix: "sudo apt install dpkg rpm makensis" -> "sudo apt install dpkg rpm nsis"
Within the Debian/Ubuntu installation guide section.

Error below:
>par@parcar-LG-Laptop:\~/Downloads$ sudo apt install dpkg rpm makensis    
>Reading package lists... Done  
>Building dependency tree    
>Reading state information... Done  
>**E: Unable to locate package makensis**  
>par@parcar-LG-Laptop:\~/Downloads$ makensis  
>The program 'makensis' is currently not installed. You can install it by typing:  
>**sudo apt install nsis**  
>par@parcar-LG-Laptop:~/Downloads$ sudo apt-get install dpkg rpm nsis  
>Reading package lists... Done
>...  
>0 upgraded, 11 newly installed, 0 to remove and 0 not upgraded.

**Comment by hensm** [comment]
Fixed, thanks! — 588c007
