### ISSUE TITLE
Disconnect / Stop casting option

### ISSUE THREAD

**Issue by jcc10** [hensm/fx_cast#50]
Add a way to disconnect / stop casting button / option so when we are done we can stop sharing.

**Comment by hensm** [comment]
Some overlap with #10.

82f68a1 — Receiver updates forwarding

Will probably want to work on separating the popup from shim scripts, so it can be used standalone. Would prefer to keep everything in one place rather than creating a new interface for it.

**Comment by hensm** [comment]
9295d8e — Implemented
(alt/opt key modifier on regular button)
