### ISSUE TITLE
[compat] Sportsnet Now

### ISSUE THREAD

**Issue by meter1060** [hensm/fx_cast#55]
**App name:** Sportsnet Now
**App URL:** https://now.sportsnet.ca/

**Issues:**
No cast button on the player when all sites added to whitelist. Uses NeuLion/Endeavor streaming. Same streaming service as NBA/UFC

**Comment by hensm** [comment]
Can't test due to region/subscription restrictions, but possibly fixed in next release.

**Comment by matmunn** [comment]
I'm interested in this as well. Any idea when next tag will go out or should I try and do my own build?

**Comment by hensm** [comment]
Still a couple of things to fix before another release. Possibly this weekend, but no guarantees.

It should be straightforward to build, if you want to do that. Node 10 isn't a requirement anymore, so you can ignore that.

**Comment by matmunn** [comment]
Using NBA for testing v0.0.4 at least now shows the cast icon in the player after being whitelisted, I can then initialise a stream.

It seems to be a little flaky, twice I had it flash the NBA logo on my receiving device and then terminate it and return to the default Chromecast screen and I'm unable to start any other streams on the device (tab, screen, or app) unless I do a hard refresh.
The third trial loaded the stream properly and started playing, which naturally. was the time I had the console open to check for errors

**Comment by hensm** [comment]
Marking as partially compatible, then. I've noticed similar behaviour on other senders, but whether it's the same issue or not, I don't know. It's been quite difficult to track down.

If you can get an error log, that would be helpful. If it fails in the bridge, the error would be printed only to the global [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console).

**Comment by meter1060** [comment]
With the release of 0.0.5 I consistently get the icon and can now cast Sportsnet Now
