### ISSUE TITLE
User Agent Whitelist breaks YouTube's "New Look"

### ISSUE THREAD

**Issue by qkflies** [hensm/fx_cast#66]
When the user agent whitelist is enabled, the user agent applied to YouTube is deemed incompatible with YouTube's "New Look," as determined by the page [youtube.com/new](https://youtube.com/new). 

While it doesn't harm actual casting functionality, it is a bit annoying to not be able to use dark mode on YouTube.

The match pattern I applied for YouTube is `https://www.youtube.com/*`.

This issue does not persist if the whitelist is disabled.

In case it helps, Firefox v67.0.1 w/ extension, bridge v0.0.3.

**Comment by hensm** [comment]
Yeah, this is intentional. The new design doesn't work without polyfills on Firefox. Changing the user agent string to Chrome completely breaks it, so I chose one old enough that it would stick to the old design.

See #12.
