### ISSUE TITLE
blank checkbox labels in Firefox on Mac OS X

### ISSUE THREAD

**Issue by autonome** [hensm/fx_cast#68]
Maybe because dark theme?

<img width="695" alt="Screen Shot 2019-06-11 at 11 03 46 AM" src="https://user-images.githubusercontent.com/50103/59295693-2b5c3b00-8c39-11e9-9187-2d4cc22f741d.png">

**Comment by hensm** [comment]
Known issue in Nightly:
https://bugzilla.mozilla.org/show_bug.cgi?id=1544212

No action needed on the extension side, though I'll probably add a dark theme for the extension UI once it becomes more clear exactly how it's going to work (system/browser theme). There are a few bugs with detecting the theme from within the options frame, too.
