### ISSUE TITLE
Update application name to be clearer than "bridge"

### ISSUE THREAD

**Issue by autonome** [hensm/fx_cast#69]
I got this prompt from the companion app. The application name should probably be clearer, like "Fx Cast" or something like that?

<img width="469" alt="Screen Shot 2019-06-11 at 11 06 36 AM" src="https://user-images.githubusercontent.com/50103/59295779-5b0b4300-8c39-11e9-9362-f504c1a83f2b.png">

**Comment by hensm** [comment]
Sounds reasonable. I'd prefer to set a friendly name, rather than just renaming the binaries, though I don't think that's possible without an app bundle.

I'll have a look, also open to suggestions.

**Comment by hensm** [comment]
53e0f865 — Fixed
