### ISSUE TITLE
Unable to uninstall it from Mac OS Mojave

### ISSUE THREAD

**Issue by DanielAlcon** [hensm/fx_cast#83]
I'm trying to uninstall it from my mac but I can't find the bridge app.

Where is it located?

Thanks

**Comment by hensm** [comment]
* `/Library/Application Support/fx_cast/`
* `/Library/Application Support/Mozilla/NativeMessagingHosts/fx_cast_bridge.json`

**Comment by DanielAlcon** [comment]
Thanks!
