### ISSUE TITLE
Error on loading add-on

### ISSUE THREAD

**Issue by jimmer74** [hensm/fx_cast#87]
Platform: Macos Mojave 10.14.6
Firefox Version: 70.0
Addon Package Version 0.4.0

Expected behaviour: 
1) pkg installation 
2) go to about:debugging to start temporary add-on installation. Navigate to ~/Library/Application\ Support/Mozilla/NativeMessagingHosts and select fx_cast_bridge.json. 
3) Add-on should install?

Actual behaviour:
1) pkg installation successful, as far as I can tell:
     fx_cast_bridge.json go to the ~/Library/Application\ Support/Mozilla/NativeMessagingHosts folder.
     fx_cast_bridge and selector executables go to ~/Library/Application\ Support/fx_cast/ folder.
2) As above.
3) Add-on does not install. Firefox fails to install add-on and complains with: 

"There was an error during the temporary add-on installation.
Error details

File /Users/jim/Library/Application Support/Mozilla/NativeMessagingHosts does not contain a valid manifest"

Without installing, there are no more enlightening messages in the console than in the Load Temporary Add-on Box.

Is there a missing manifest.json file? I have verified that the pkg file doesn't contain one using the apple-supplied  pkgutil. And you can't simply rename the fx_cast_bridge.json as a manifest file because it misses out a few required fields (which I added), but then fails due to inclusion of other fields that are not in the manifest spec. 

I'm either doing something stupid, or missing something simple. Can anyone point me in the right direction. Want to leave Chrome behind asap and this is the one thing that I "need" Chrome for....

**Comment by hensm** [comment]
The extension isn't bundled with the Installer package, it's a separate download:
https://github.com/hensm/fx_cast/releases/download/v0.0.4/fx_cast-0.0.4-fx.xpi

Perhaps I ought to add more detail to the installation section of the README. The usage section is potentially confusing, too.

**Comment by jimmer74** [comment]
Ha! I knew I was being a numpty...

Hopefully, this can serve as a signpost for people as easily confused as me until the README is updated!

Many thanks.
