### ISSUE TITLE
Build 32-bit versions for Windows

### ISSUE THREAD

**Issue by hensm** [hensm/fx_cast#88]

**Comment by shahdeys** [comment]
@hensm Is it possible please, for you to modify this to support x64 Windows 10 builds? 

C:\Users\<myusername>npm -v
6.9.0

C:\Users\myusername>node --version
v10.16.2

I feel like these should be sufficient for building. However it's not working at all.

Sifted through the code manually and things look good - but I'd be more comfortable if there was a way to get this working without trusting the releases page ;) 

Sincerely,

A Fan 👍

**Comment by hensm** [comment]
It's hardcoded to use Node 12 right now for the [prebuilt binaries](https://github.com/vercel/pkg-fetch/releases), just to make things simpler. It's a mismatch between the `NODE_MODULE_VERSION` (64/72) with the packaged version and your local version causing the issue.

You can change that here, either to `node10` or remove it entirely:
https://github.com/hensm/fx_cast/blob/01e30bca58b87325ee8a0f8663eeadbb564a8eeb/app/bin/build.js#L198

Also, if you don't want to trust the prebuilt binaries that pkg uses, you can also add the `--build` option in the same place in the build script and it'll compile its own version of Node.

**Comment by shahdeys** [comment]
Ty!!!

**Comment by hensm** [comment]
94b8ae5 — Fixed
