### ISSUE TITLE
doc bug: Extension doesn't appear in firefox 72.0.1 64bit Ubuntu 18.04.3

### ISSUE THREAD

**Issue by whitis** [hensm/fx_cast#96]
Installing fx_cast using instructions in readme on github doesn't work.

cd /dist 
sudo wget https://github.com/hensm/fx_cast/releases/download/v0.0.4/fx_cast_bridge-0.0.4-x64.deb
sudo dpkg -i fx_cast_bridge-0.0.4-x64.deb 
dpkg --listfiles fx-cast-bridge
/.
/opt
/opt/fx_cast
/opt/fx_cast/fx_cast_bridge
/usr
/usr/lib
/usr/lib/mozilla
/usr/lib/mozilla/native-messaging-hosts
/usr/lib/mozilla/native-messaging-hosts/fx_cast_bridge.json
 cat /usr/lib/mozilla/native-messaging-hosts//fx_cast_bridge.json 
{
    "name": "fx_cast_bridge",
    "description": "",
    "type": "stdio",
    "allowed_extensions": [
        "fx_cast@matt.tf"
    ],
    "path": "/opt/fx_cast/fx_cast_bridge"

Quit firefox and restarted.   fx_cast doesn't appear in addons.   Trying to manually install it from /usr/lbi/mozilla/native-messaging-hosts/fx-cast doesn't work either (says corrupt).   

had to go to  https://hensm.github.io/fx_cast/
and install extension found there.   Now an icon appears in upper right.  

Still can't actually cast anything though, so I don't know if installation is ik.   Trying to cast from youtube.com to youtube on Fire TV stick.  
Click on fx_cast icon it gives me:
   Cast  v Tab  to  (blank)
    If I pull down Tab, all the options are greyed out

I have 3 Gen 3  fire TV sticks, 1 fire TV stick 4k. and 1 gen 1? stick with voice remote upgrade  and a roku 2 xs connected via WiFi to same router (Linksys E2500) that this is computer is connected to via ethernet.  All show up on the youtube app on my phone and none show up in fx_cast.   Adding https://www.youtube.com/* to whitelist doesn't help.   Netflix also has the same problem but there are two cast buttons there (1 in firefox toolbar and one in netflix player).   Youtube can see the devices from google chrome from the same machine and I can cast aside from some idiot at youtube asking "Who's watching"" on a non-shared device and not being near the remote.    Remoku extentension (roku remote) on chrome did have trouble finding rokus automatically but worked if you manually entered the IP address.   So it might not be the easiest router to do upnp/dlna device discovery through.  Router settings: UPnP Enabled, allow users to configure enabled, allow users to disable internet access disabled.    There are 15 devices on the network.

This is what the nearest firetv stick looks ike to gssdp-discover from the same machine:
resource available
  USN:      uuid:53f1e401-7948-1e95-0000-000008902ab1::urn:dial-multiscreen-org:service:dial:1
  Location: http://192.168.1.144:60000/upnp/dev/53f1e401-7948-1e95-0000-000008902ab1/desc

**Comment by hensm** [comment]
The README mentions that there are two separate components with their own installation step. The Debian package is just the bridge application and doesn't include a sideloaded extension.

The Fire TV doesn't have Chromecast support, but instead uses DIAL. Some apps support both Chromecast and DIAL (like YouTube), but there's no support for that in this extension. I'm not opposed to supporting it (#54), but I haven't looked into it, nor do I have any test devices for it.

I don't _think_ any of the devices you mentioned are actually Chromecast-enabled, though the cast button in the Netflix player toolbar should only appear if there are valid receivers found, which is puzzling.

When you say the popup is blank, you mean it's like [this](https://hensm.github.io/fx_cast/images/preview-fg_macOS_dark@2x.png), but with just the top section?

The confusion around the casting methods and how you're supposed to cast different types of media is addressed here (and fixed for the next release):
[https://hensm.github.io/fx_cast/#How_do_I_cast_something?](https://hensm.github.io/fx_cast/#How_do_I_cast_something?)
